---

openssl_certs:
  - name: http
    key_path: "/etc/openssl/certs"
    key_type: RSA
    key_size: 4096
    key_passphrase: "HTTP_host1_PrivateKeyPassphraseHere"
    cert_path: "/etc/openssl/certs"
    cert_expire: "+365d"
    permission_mode: "0640"
    permission_user: "root"
    permission_group: "root"
    cert_subject_alt_name:
      - "IP:127.0.0.1"
      - "IP:{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      - "DNS:{{ ansible_hostname }}"
      - "DNS:localhost"
      - "DNS:{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    cert_common_name: "{{ ansible_hostname }}"
    basic_constraints:
      - "CA:FALSE"
    basic_constraints_critical: false
    key_usage: ["digitalSignature", "keyEncipherment"]
    key_usage_critical: true
    extended_key_usage: ["serverAuth", "clientAuth"]
    extended_key_usage_critical: true
    ocsp_must_staple: false
    ocsp_must_staple_critical: false
    copy_ca_path: "/etc/openssl/certs"
    export_to_pkcs12: yes
    ca_issuer:
      cert_path: "/etc/openssl/certs/intermediate-ca.crt"
      key_path: "/etc/openssl/certs/intermediate-ca.key"
      key_passphrase: "IntermediatePrivateKeyPassphraseHere"
      issued_ca_host: "intermediate_ca_host"
      bundle_path: /etc/openssl/certs/ca-bundle.crt

openssl_copy_ca:
  src_host: intermediate_ca_host
  src: "/etc/openssl/certs/ca-bundle.crt"
  dest: "/etc/openssl/certs/ca-bundle2.crt"
